Tweak
nntuyen/text-decorator pull request #4
Opened 2017-03-13 15:10 UTC by jonathan-caryl

Hi @nntuyen , I saw your library on Android Weekly — looks useful

Anyway, I made a few tweaks, hope the PR's ok.

2017-03-18 16:30 UTC, jamesnguyenhub requested changes

2017-03-18 16:30 UTC, nntuyen commented on build.gradle
> +ext {
It's nice @jonathan-caryl. But the build got failed. Please fix it before I can merge :)

2017-03-20 09:28 UTC, jonathan-caryl commented
@nntuyen updated the `.travis.yml` and the build's now passing

2017-03-20 22:26 UTC, jamesnguyenhub approved these changes

2017-03-20 22:26 UTC, merged